sudo: required
services: 
  - docker
before_install: 
  - docker build -t harshith24/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true harshith24/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-434210047159"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"